import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

type Language = 'en' | 'ur'

interface LanguageContextValue {
  language: Language
  setLanguage: (value: Language) => void
  isUrdu: boolean
  dir: 'ltr' | 'rtl'
  t: (path: string) => string
}

const translations = {
  en: {
    common: {
      cancel: 'Cancel',
      save: 'Save',
      saveSettings: 'Save Settings',
      loading: 'Loading settings...',
      noData: 'No entries yet.',
      notifications: 'Notifications',
      emptyNotifications: 'No notifications yet.',
      englishUrdu: 'English / اردو',
      search: 'Search',
      date: 'Date',
      customer: 'Customer',
      mode: 'Mode',
      labourAmount: 'Labour Amount',
      balance: 'Balance',
      enteredBy: 'Entered By',
      totalCashIn: 'Total Cash In',
      totalCashOut: 'Total Cash Out',
      finalBalance: 'Final Balance',
      totalEntries: 'Total Entries',
      export: 'Export',
      print: 'Print',
      settings: 'Settings',
      reportTitle: 'Report',
      remark: 'Remark / Customer',
      goldReceived: 'Gold Received',
      goldGiven: 'Gold Given',
      cashIn: 'Cash In',
      cashOut: 'Cash Out',
      report: 'Report',
    },
    nav: {
      dashboard: 'Dashboard',
      customers: 'Customers',
      entries: 'Entries',
      calculator: 'Calculator',
      reports: 'Reports',
      activityLog: 'Activity Log',
      settings: 'Settings',
      adminPanel: 'Admin Panel',
    },
    customerForm: {
      fullName: 'Full Name',
      phoneNumber: 'Phone Number',
      whatsappNumber: 'WhatsApp Number',
      city: 'City',
      address: 'Address',
      notes: 'Notes',
      customerPhoto: 'Customer photo',
      uploadPhoto: 'Upload photo',
      noPhotoSelected: 'No photo selected yet.',
      cancel: 'Cancel',
      addCustomer: 'Add Customer',
      updateCustomer: 'Update Customer',
    },
    entryForm: {
      customer: 'Customer',
      searchCustomer: 'Search customer',
      selectCustomer: 'Select a customer',
      createCustomerBefore: 'Create a customer before adding an entry.',
      createCustomer: 'Create customer',
      date: 'Date',
      direction: 'Direction',
      goldReceived: 'Gold Received',
      goldGiven: 'Gold Given',
      entryMode: 'Entry Mode',
      goldOnly: 'Gold Only',
      labourOnly: 'Labour Only',
      goldPlusLabour: 'Gold + Labour',
      conversionFormula: 'Conversion Formula',
      twentyFourKWeight: '24K Weight (g)',
      twentyOneKWeight: '21K Weight (g)',
      twentyOneKLabourWeight: '21K Labour Weight (g)',
      labourRate: 'Labour Rate (SAR/g)',
      labourAmount: 'Labour Amount',
      enableVat: 'Enable VAT',
      enableInvoice: 'Enable Invoice',
      invoiceNumber: 'Invoice Number',
      gold: 'Gold',
      labour: 'Labour',
      vat: 'VAT',
      invoice: 'Invoice',
      grandTotal: 'Grand Total',
      uploadPhotoHint: 'Click to upload or drag and drop photos',
      notes: 'Notes',
      cancel: 'Cancel',
      addEntry: 'Add Entry',
      updateEntry: 'Update Entry',
    },
    reports: {
      title: 'Workshop reports and exports',
      description: 'Review day-to-day movement, customer activity, labour, VAT, and invoices with filters and export support.',
      filters: 'Report filters',
      reportType: 'Report type',
      startDate: 'Start date',
      endDate: 'End date',
      customer: 'Customer',
      direction: 'Direction',
      entryMode: 'Entry mode',
      invoice: 'Invoice',
      resetFilters: 'Reset filters',
      total24kReceived: 'Total 24K received',
      total21kReceived: 'Total 21K received',
      total24kGiven: 'Total 24K given',
      total21kGiven: 'Total 21K given',
      netGoldBalance: 'Net gold balance',
      totalLabour: 'Total labour',
      totalVat: 'Total VAT',
      grandTotal: 'Grand total',
      entryCount: 'Entry count',
      printReport: 'Print report',
      exportCsv: 'Export CSV',
      noEntries: 'No matching entries for the current filters.',
      cashBook: 'Cash Book',
      cashBookHint: 'A simple cashbook view for workshop movement and balances.',
      remark: 'Remark / Customer',
      mode: 'Mode',
      date: 'Date',
      goldReceived: 'Gold Received',
      goldGiven: 'Gold Given',
      labourAmount: 'Labour Amount',
      cashIn: 'Cash In',
      cashOut: 'Cash Out',
      balance: 'Balance',
      enteredBy: 'Entered By',
      totalCashIn: 'Total Cash In',
      totalCashOut: 'Total Cash Out',
      finalBalance: 'Final Balance',
      totalEntries: 'Total Entries',
    },
    settings: {
      title: 'Workshop settings',
      description: 'Configure your workshop information, business rules, and system preferences.',
      workshopInfo: 'Workshop Information',
      workshopName: 'Workshop Name',
      phone: 'Phone',
      address: 'Address',
      businessRules: 'Business Rules',
      vatPercentage: 'VAT Percentage',
      currency: 'Currency',
      defaultFormula: 'Default Gold Conversion Formula',
      dataManagement: 'Data Management',
      dataDescription: 'Export your data, import previously exported data, or clear all data from the system.',
      exportData: 'Export Data',
      importData: 'Import Data',
      backupJson: 'Backup JSON',
      restoreBackup: 'Restore Backup',
      clearAllData: 'Clear All Data',
      clearAllTitle: 'Clear all data',
      clearAllDescription: 'This will permanently delete all entries, customers, and settings. This action cannot be undone.',
      confirmClearAll: 'Clear All',
      cancel: 'Cancel',
      saveSettings: 'Save Settings',
    },
  },
  ur: {
    common: {
      cancel: 'منسوخ',
      save: 'محفوظ کریں',
      saveSettings: 'ترتیبات محفوظ کریں',
      loading: 'ترتیبات لوڈ ہو رہی ہیں...',
      noData: 'ابھی کوئی اندراج نہیں۔',
      notifications: 'اطلاعات',
      emptyNotifications: 'ابھی کوئی اطلاعات نہیں۔',
      englishUrdu: 'English / اردو',
      search: 'تلاش',
      date: 'تاریخ',
      customer: 'نام / تفصیل',
      mode: 'قسم',
      labourAmount: 'مزدوری',
      balance: 'بقایا',
      enteredBy: 'درج کرنے والا',
      totalCashIn: 'کل رقم وصول',
      totalCashOut: 'کل رقم ادا',
      finalBalance: 'آخری بقایا',
      totalEntries: 'کل اندراجات',
      export: 'برآمد',
      print: 'پرنٹ',
      settings: 'ترتیبات',
      reportTitle: 'رپورٹ',
      remark: 'نام / تفصیل',
      goldReceived: 'سونا وصول',
      goldGiven: 'سونا دیا',
      cashIn: 'رقم وصول',
      cashOut: 'رقم ادا',
      report: 'رپورٹ',
    },
    nav: {
      dashboard: 'ڈیش بورڈ',
      customers: 'مشتریان',
      entries: 'اندراج',
      calculator: 'کیلکولیٹر',
      reports: 'رپورٹس',
      activityLog: 'سرگرمی لاگ',
      settings: 'ترتیبات',
      adminPanel: 'ایڈمن پینل',
    },
    customerForm: {
      fullName: 'پورا نام',
      phoneNumber: 'فون نمبر',
      whatsappNumber: 'واٹس ایپ نمبر',
      city: 'شہر',
      address: 'پتہ',
      notes: 'نوٹس',
      customerPhoto: 'مشتری کی تصویر',
      uploadPhoto: 'تصویر اپ لوڈ کریں',
      noPhotoSelected: 'ابھی کوئی تصویر منتخب نہیں۔',
      cancel: 'منسوخ',
      addCustomer: 'مشتری شامل کریں',
      updateCustomer: 'مشتری کی اطلاعات اپ ڈیٹ کریں',
    },
    entryForm: {
      customer: 'مشتری',
      searchCustomer: 'مشتری تلاش کریں',
      selectCustomer: 'مشتری منتخب کریں',
      createCustomerBefore: 'اندراج شامل کرنے سے پہلے ایک مشتری پیدا کریں۔',
      createCustomer: 'مشتری بنائیں',
      date: 'تاریخ',
      direction: 'سمت',
      goldReceived: 'سونا وصول',
      goldGiven: 'سونا دیا',
      entryMode: 'اندراج کی قسم',
      goldOnly: 'صرف سونا',
      labourOnly: 'صرف مزدوری',
      goldPlusLabour: 'سونا + مزدوری',
      conversionFormula: 'تبدیلی کا فارمولا',
      twentyFourKWeight: '24K وزن (g)',
      twentyOneKWeight: '21K وزن (g)',
      twentyOneKLabourWeight: '21K مزدوری وزن (g)',
      labourRate: 'مزدوری کی شرح (SAR/g)',
      labourAmount: 'مزدوری',
      enableVat: 'وی اے ٹی فعال کریں',
      enableInvoice: 'انوائس فعال کریں',
      invoiceNumber: 'انوائس نمبر',
      gold: 'سونا',
      labour: 'مزدوری',
      vat: 'وی اے ٹی',
      invoice: 'انوائس',
      grandTotal: 'کل رقم',
      uploadPhotoHint: 'تصاویر اپ لوڈ کرنے کے لیے یہاں کلک کریں',
      notes: 'نوٹس',
      cancel: 'منسوخ',
      addEntry: 'اندراج شامل کریں',
      updateEntry: 'اندراج اپ ڈیٹ کریں',
    },
    reports: {
      title: 'کارخانہ کی رپورٹس اور برآمد',
      description: 'روزانہ، گاہکوں، مزدوری، وی اے ٹی اور انوائس کی معلومات فلٹرز کے ساتھ دیکھیں۔',
      filters: 'رپورٹ فلٹرز',
      reportType: 'رپورٹ کی قسم',
      startDate: 'آغاز کی تاریخ',
      endDate: 'اختتام کی تاریخ',
      customer: 'مشتری',
      direction: 'سمت',
      entryMode: 'اندراج کی قسم',
      invoice: 'انوائس',
      resetFilters: 'فلٹر دوبارہ سیٹ کریں',
      total24kReceived: 'کل 24K وصول',
      total21kReceived: 'کل 21K وصول',
      total24kGiven: 'کل 24K دیا',
      total21kGiven: 'کل 21K دیا',
      netGoldBalance: 'خالص سونے کا بقایا',
      totalLabour: 'کل مزدوری',
      totalVat: 'کل وی اے ٹی',
      grandTotal: 'آخری کل',
      entryCount: 'اندراجات کی تعداد',
      printReport: 'رپورٹ پرنٹ کریں',
      exportCsv: 'CSV برآمد کریں',
      noEntries: 'اس فلٹر کے لیے کوئی اندراج نہیں۔',
      cashBook: 'کیش بک',
      cashBookHint: 'کارخانے کی نقل و حرکت اور بقایا کے لیے ایک سادہ کیش بک منظر۔',
      remark: 'نام / تفصیل',
      mode: 'قسم',
      date: 'تاریخ',
      goldReceived: 'سونا وصول',
      goldGiven: 'سونا دیا',
      labourAmount: 'مزدوری',
      cashIn: 'رقم وصول',
      cashOut: 'رقم ادا',
      balance: 'بقایا',
      enteredBy: 'درج کرنے والا',
      totalCashIn: 'کل رقم وصول',
      totalCashOut: 'کل رقم ادا',
      finalBalance: 'آخری بقایا',
      totalEntries: 'کل اندراجات',
    },
    settings: {
      title: 'کارخانے کی ترتیبات',
      description: 'اپنے ورکشاپ کی معلومات، کاروباری اصول اور سسٹم کی ترجیحات کو ترتیب دیں۔',
      workshopInfo: 'ورکشاپ کی معلومات',
      workshopName: 'ورکشاپ کا نام',
      phone: 'فون',
      address: 'پتہ',
      businessRules: 'کاروباری اصول',
      vatPercentage: 'وی اے ٹی فیصد',
      currency: 'کرنسی',
      defaultFormula: 'پہلے سے طے شدہ سونے کی تبدیلی کا فارمولا',
      dataManagement: 'ڈیٹا مینجمنٹ',
      dataDescription: 'اپنا ڈیٹا برآمد کریں، پہلے سے محفوظ شدہ ڈیٹا درآمد کریں یا مکمل ڈیٹا حذف کریں۔',
      exportData: 'ڈیٹا برآمد کریں',
      importData: 'ڈیٹا درآمد کریں',
      backupJson: 'بیک اپ JSON',
      restoreBackup: 'بیک اپ بحال کریں',
      clearAllData: 'سارا ڈیٹا صاف کریں',
      clearAllTitle: 'سارا ڈیٹا صاف کریں',
      clearAllDescription: 'یہ تمام اندراجات، مشتریوں اور ترتیبات کو مستقل طور پر حذف کر دے گا۔',
      confirmClearAll: 'سارا ڈیٹا صاف کریں',
      cancel: 'منسوخ',
      saveSettings: 'ترتیبات محفوظ کریں',
    },
  },
} as const

function getValue(value: Record<string, unknown>, path: string) {
  return path.split('.').reduce<unknown>((current, key) => (current && typeof current === 'object' ? (current as Record<string, unknown>)[key] : undefined), value) as string | undefined
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'en'
    const stored = window.localStorage.getItem('shaibha-language')
    return stored === 'ur' ? 'ur' : 'en'
  })

  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.localStorage.setItem('shaibha-language', language)
    }
    document.documentElement.lang = language === 'ur' ? 'ur' : 'en'
    document.documentElement.dir = language === 'ur' ? 'rtl' : 'ltr'
  }, [language])

  const setLanguage = (value: Language) => setLanguageState(value)

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    isUrdu: language === 'ur',
    dir: language === 'ur' ? 'rtl' : 'ltr',
    t: (path: string) => {
      const section = translations[language]
      return getValue(section as Record<string, unknown>, path) ?? getValue(translations.en as Record<string, unknown>, path) ?? path
    },
  }), [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
