import { createContext, useContext, useEffect, useMemo, useState } from 'react'

type Language = 'en' | 'ur'

interface LanguageContextValue {
  language: Language
  isUrdu: boolean
  dir: 'ltr' | 'rtl'
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    appTitle: 'Shaibah Warsha',
    appSubtitle: 'Gold Workshop',
    toggleLanguage: 'اردو',
    nav.dashboard: 'Dashboard',
    nav.customers: 'Customers',
    nav.entries: 'Entries',
    nav.calculator: 'Calculator',
    nav.reports: 'Reports',
    nav.activity: 'Activity Log',
    nav.settings: 'Settings',
    nav.admin: 'Admin Panel',
    topbar.notifications: 'Notifications',
    topbar.settings: 'Settings',
    topbar.searchPlaceholder: 'Search records',
    buttons.cancel: 'Cancel',
    buttons.save: 'Save',
    buttons.update: 'Update',
    buttons.addCustomer: 'Add Customer',
    buttons.updateCustomer: 'Update Customer',
    buttons.addEntry: 'Add Entry',
    buttons.updateEntry: 'Update Entry',
    buttons.createCustomer: 'Create customer',
    buttons.print: 'Print',
    buttons.csv: 'CSV',
    buttons.json: 'JSON',
    buttons.resetFilters: 'Reset filters',
    customerForm.title: 'Customer Details',
    customerForm.fullName: 'Full Name',
    customerForm.phone: 'Phone Number',
    customerForm.whatsapp: 'WhatsApp Number',
    customerForm.city: 'City',
    customerForm.address: 'Address',
    customerForm.notes: 'Notes',
    customerForm.photo: 'Customer photo',
    customerForm.uploadPhoto: 'Upload photo',
    customerForm.noPhoto: 'No photo selected yet.',
    entryForm.customer: 'Customer',
    entryForm.customerPrompt: 'Create a customer before adding an entry.',
    entryForm.searchCustomer: 'Search customer',
    entryForm.selectCustomer: 'Select a customer',
    entryForm.date: 'Date',
    entryForm.direction: 'Direction',
    entryForm.directionReceive: 'Gold Received',
    entryForm.directionGive: 'Gold Given',
    entryForm.entryMode: 'Entry Mode',
    entryForm.modeGold: 'Gold Only',
    entryForm.modeLabour: 'Labour Only',
    entryForm.modeBoth: 'Gold + Labour',
    entryForm.formula: 'Conversion Formula',
    entryForm.weight24k: '24K Weight (g)',
    entryForm.weight21k: '21K Weight (g)',
    entryForm.labourWeight: '21K Labour Weight (g)',
    entryForm.labourRate: 'Labour Rate (SAR/g)',
    entryForm.labourAmount: 'Labour Amount',
    entryForm.vat: 'Enable VAT',
    entryForm.invoice: 'Enable Invoice',
    entryForm.invoiceNumber: 'Invoice Number',
    entryForm.notes: 'Notes',
    entryForm.goldSummary: 'Gold',
    entryForm.labourSummary: 'Labour',
    entryForm.vatSummary: 'VAT',
    entryForm.invoiceSummary: 'Invoice',
    entryForm.grandTotal: 'Grand Total',
    entryForm.uploadPhotos: 'Click to upload or drag and drop photos',
    reports.title: 'Workshop reports and exports',
    reports.description: 'Review day-to-day movement, customer activity, labour, VAT, and invoices with filters and export support.',
    reports.filters: 'Report filters',
    reports.reportType: 'Report type',
    reports.startDate: 'Start date',
    reports.endDate: 'End date',
    reports.customer: 'Customer',
    reports.direction: 'Direction',
    reports.directionAll: 'All directions',
    reports.entryMode: 'Entry mode',
    reports.invoice: 'Invoice',
    reports.reset: 'Reset filters',
    reports.summary: 'Summary',
    reports.print: 'Print report',
    reports.exportCsv: 'Export CSV',
    reports.exportJson: 'Export JSON',
    reports.noData: 'No matching entries for the current filters.',
    reports.tableDate: 'Date',
    reports.tableCustomer: 'Remark / Customer',
    reports.tableDirection: 'Mode',
    reports.tableMode: 'Mode',
    reports.table24k: '24K',
    reports.table21k: '21K',
    reports.tableLabour: 'Labour',
    reports.tableVat: 'VAT',
    reports.tableGrand: 'Grand total',
    reports.tableInvoice: 'Invoice',
    reports.total24kReceived: 'Total 24K received',
    reports.total21kReceived: 'Total 21K received',
    reports.total24kGiven: 'Total 24K given',
    reports.total21kGiven: 'Total 21K given',
    reports.netGold: 'Net gold balance',
    reports.totalLabour: 'Total labour',
    reports.totalVat: 'Total VAT',
    reports.grandTotal: 'Grand total',
    reports.entryCount: 'Entry count',
    reports.businessName: 'Shaibah Warsha',
    reports.printTitle: 'Report',
    reports.printGenerated: 'Generated',
    reports.allDates: 'All dates',
    settings.title: 'Workshop settings',
    settings.description: 'Configure your workshop information, business rules, and system preferences.',
    settings.workshopInfo: 'Workshop Information',
    settings.workshopName: 'Workshop Name',
    settings.phone: 'Phone',
    settings.address: 'Address',
    settings.businessRules: 'Business Rules',
    settings.vatPercentage: 'VAT Percentage',
    settings.currency: 'Currency',
    settings.formula: 'Default Gold Conversion Formula',
    settings.dataManagement: 'Data Management',
    settings.dataDescription: 'Export your data, import previously exported data, or clear all data from the system.',
    settings.exportData: 'Export Data',
    settings.importData: 'Import Data',
    settings.backupJson: 'Backup JSON',
    settings.restoreBackup: 'Restore Backup',
    settings.clearData: 'Clear All Data',
    settings.save: 'Save Settings',
    settings.loading: 'Loading settings...',
    notifications.empty: 'No notifications yet.',
    notifications.title: 'Notifications',
    ledger.customerStatement: 'Customer statement',
    ledger.print: 'Print',
    ledger.exportCsv: 'CSV',
    ledger.exportJson: 'JSON',
    ledger.searchPlaceholder: 'Search by invoice or notes',
    cashbook.date: 'Date',
    cashbook.remark: 'Remark / Customer',
    cashbook.mode: 'Mode',
    cashbook.goldReceived: 'Gold Received',
    cashbook.goldGiven: 'Gold Given',
    cashbook.labour: 'Labour Amount',
    cashbook.cashIn: 'Cash In',
    cashbook.cashOut: 'Cash Out',
    cashbook.balance: 'Balance',
    cashbook.enteredBy: 'Entered By',
    cashbook.totalCashIn: 'Total Cash In',
    cashbook.totalCashOut: 'Total Cash Out',
    cashbook.finalBalance: 'Final Balance',
    cashbook.totalEntries: 'Total Entries',
    activity.search: 'Search',
    activity.actions: 'Action',
    activity.startDate: 'Start date',
    activity.endDate: 'End date',
    activity.clearLog: 'Clear log',
    admin.totalCustomers: 'Total customers',
    admin.totalEntries: 'Total entries',
    admin.storageUsed: 'Storage used',
    admin.lastBackup: 'Last backup/export',
    admin.health: 'Data health check',
    admin.backupRestore: 'Backup & restore',
    admin.exportBackup: 'Download full backup JSON',
    admin.importBackup: 'Restore from backup JSON',
    admin.clearAll: 'Clear all data',
  },
  ur: {
    appTitle: 'شایبہ ورشہ',
    appSubtitle: 'سونا ورکشاپ',
    toggleLanguage: 'English',
    nav.dashboard: 'ڈیش بورڈ',
    nav.customers: 'گاہک',
    nav.entries: 'اندراجات',
    nav.calculator: 'کیلکولیٹر',
    nav.reports: 'رپورٹس',
    nav.activity: 'سراغی لاگ',
    nav.settings: 'ترتیبات',
    nav.admin: 'ایڈمن پینل',
    topbar.notifications: 'اطلاعات',
    topbar.settings: 'ترتیبات',
    topbar.searchPlaceholder: 'ریکارڈز تلاش کریں',
    buttons.cancel: 'منسوخ',
    buttons.save: 'محفوظ کریں',
    buttons.update: 'تازہ کریں',
    buttons.addCustomer: 'گاہک شامل کریں',
    buttons.updateCustomer: 'گاہک تازہ کریں',
    buttons.addEntry: 'اندراج شامل کریں',
    buttons.updateEntry: 'اندراج تازہ کریں',
    buttons.createCustomer: 'گاہک بنائیں',
    buttons.print: 'پرنٹ',
    buttons.csv: 'CSV',
    buttons.json: 'JSON',
    buttons.resetFilters: 'فلٹر دوبارہ سیٹ کریں',
    customerForm.title: 'گاہک کی تفصیلات',
    customerForm.fullName: 'پورا نام',
    customerForm.phone: 'فون نمبر',
    customerForm.whatsapp: 'واٹس ایپ نمبر',
    customerForm.city: 'شہر',
    customerForm.address: 'پتہ',
    customerForm.notes: 'نوٹس',
    customerForm.photo: 'گاہک کی تصویر',
    customerForm.uploadPhoto: 'تصویر اپ لوڈ کریں',
    customerForm.noPhoto: 'ابھی تک کوئی تصویر منتخب نہیں کی گئی۔',
    entryForm.customer: 'گاہک',
    entryForm.customerPrompt: 'اندراج شامل کرنے سے پہلے گاہک بنائیں۔',
    entryForm.searchCustomer: 'گاہک تلاش کریں',
    entryForm.selectCustomer: 'گاہک منتخب کریں',
    entryForm.date: 'تاریخ',
    entryForm.direction: 'سمت',
    entryForm.directionReceive: 'سونا وصول',
    entryForm.directionGive: 'سونا دیا',
    entryForm.entryMode: 'اندراج کی قسم',
    entryForm.modeGold: 'صرف سونا',
    entryForm.modeLabour: 'صرف مزدوری',
    entryForm.modeBoth: 'سونا + مزدوری',
    entryForm.formula: 'تبدیلی فارمولہ',
    entryForm.weight24k: '24K وزن (g)',
    entryForm.weight21k: '21K وزن (g)',
    entryForm.labourWeight: '21K مزدوری وزن (g)',
    entryForm.labourRate: 'مزدوری کی شرح (SAR/g)',
    entryForm.labourAmount: 'مزدوری',
    entryForm.vat: 'وی اے ٹی فعال کریں',
    entryForm.invoice: 'انوائس فعال کریں',
    entryForm.invoiceNumber: 'انوائس نمبر',
    entryForm.notes: 'نوٹس',
    entryForm.goldSummary: 'سونا',
    entryForm.labourSummary: 'مزدوری',
    entryForm.vatSummary: 'وی اے ٹی',
    entryForm.invoiceSummary: 'انوائس',
    entryForm.grandTotal: 'کل رقم',
    entryForm.uploadPhotos: 'تصاویر اپ لوڈ کرنے کے لیے کلک کریں',
    reports.title: 'ورکشاپ رپورٹس اور ایکسپورٹس',
    reports.description: 'روزمرہ کی نقل و حرکت، گاہک کی سرگرمی، مزدوری، وی اے ٹی اور انوائس کو فلٹرز اور ایکسپورٹس کے ساتھ دیکھیں۔',
    reports.filters: 'رپورٹ فلٹرز',
    reports.reportType: 'رپورٹ کی قسم',
    reports.startDate: 'شروع کی تاریخ',
    reports.endDate: 'اختتامی تاریخ',
    reports.customer: 'گاہک',
    reports.direction: 'سمت',
    reports.directionAll: 'تمام سمتیں',
    reports.entryMode: 'اندراج کی قسم',
    reports.invoice: 'انوائس',
    reports.reset: 'فلٹر دوبارہ سیٹ کریں',
    reports.summary: 'خلاصہ',
    reports.print: 'رپورٹ پرنٹ کریں',
    reports.exportCsv: 'CSV ایکسپورٹ',
    reports.exportJson: 'JSON ایکسپورٹ',
    reports.noData: 'موجودہ فلٹرز کے لیے کوئی میچ کرنے والا اندراج نہیں۔',
    reports.tableDate: 'تاریخ',
    reports.tableCustomer: 'نام / تفصیل',
    reports.tableDirection: 'قسم',
    reports.tableMode: 'قسم',
    reports.table24k: '24K',
    reports.table21k: '21K',
    reports.tableLabour: 'مزدوری',
    reports.tableVat: 'وی اے ٹی',
    reports.tableGrand: 'کل رقم',
    reports.tableInvoice: 'انوائس',
    reports.total24kReceived: 'کل 24K وصول',
    reports.total21kReceived: 'کل 21K وصول',
    reports.total24kGiven: 'کل 24K دیا',
    reports.total21kGiven: 'کل 21K دیا',
    reports.netGold: 'خالص سونا بقایا',
    reports.totalLabour: 'کل مزدوری',
    reports.totalVat: 'کل وی اے ٹی',
    reports.grandTotal: 'کل رقم',
    reports.entryCount: 'کل اندراجات',
    reports.businessName: 'شایبہ ورشہ',
    reports.printTitle: 'رپورٹ',
    reports.printGenerated: 'تیار',
    reports.allDates: 'تمام تاریخیں',
    settings.title: 'ورکشاپ ترتیبات',
    settings.description: 'اپنی ورکشاپ کی معلومات، کاروباری قواعد اور سسٹم کی ترجیحات کو تشکیل دیں۔',
    settings.workshopInfo: 'ورکشاپ کی معلومات',
    settings.workshopName: 'ورکشاپ کا نام',
    settings.phone: 'فون',
    settings.address: 'پتہ',
    settings.businessRules: 'کاروباری قواعد',
    settings.vatPercentage: 'وی اے ٹی فیصد',
    settings.currency: 'کرنسی',
    settings.formula: 'پہلے سے طے شدہ سونا تبادلہ فارمولہ',
    settings.dataManagement: 'ڈیٹا مینجمنٹ',
    settings.dataDescription: 'اپنا ڈیٹا ایکسپورٹ کریں، پہلے سے ایکسپورٹ شدہ ڈیٹا درآمد کریں، یا پورا ڈیٹا حذف کریں۔',
    settings.exportData: 'ڈیٹا ایکسپورٹ',
    settings.importData: 'ڈیٹا درآمد',
    settings.backupJson: 'بیک اپ JSON',
    settings.restoreBackup: 'بیک اپ بحال',
    settings.clearData: 'پورا ڈیٹا صاف کریں',
    settings.save: 'ترتیبات محفوظ کریں',
    settings.loading: 'ترتیبات لوڈ ہو رہی ہیں…',
    notifications.empty: 'ابھی تک کوئی اطلاعات نہیں۔',
    notifications.title: 'اطلاعات',
    ledger.customerStatement: 'گاہک کا بیان',
    ledger.print: 'پرنٹ',
    ledger.exportCsv: 'CSV',
    ledger.exportJson: 'JSON',
    ledger.searchPlaceholder: 'انوائس یا نوٹس سے تلاش کریں',
    cashbook.date: 'تاریخ',
    cashbook.remark: 'نام / تفصیل',
    cashbook.mode: 'قسم',
    cashbook.goldReceived: 'سونا وصول',
    cashbook.goldGiven: 'سونا دیا',
    cashbook.labour: 'مزدوری',
    cashbook.cashIn: 'رقم وصول',
    cashbook.cashOut: 'رقم ادا',
    cashbook.balance: 'بقایا',
    cashbook.enteredBy: 'درج کرنے والا',
    cashbook.totalCashIn: 'کل رقم وصول',
    cashbook.totalCashOut: 'کل رقم ادا',
    cashbook.finalBalance: 'آخری بقایا',
    cashbook.totalEntries: 'کل اندراجات',
    activity.search: 'تلاش',
    activity.actions: 'عمل',
    activity.startDate: 'شروع کی تاریخ',
    activity.endDate: 'اختتامی تاریخ',
    activity.clearLog: 'لاگ صاف کریں',
    admin.totalCustomers: 'کل گاہک',
    admin.totalEntries: 'کل اندراجات',
    admin.storageUsed: 'استعمال شدہ اسٹوریج',
    admin.lastBackup: 'آخری بیک اپ/ایکسپورٹ',
    admin.health: 'ڈیٹا ہیلتھ چیک',
    admin.backupRestore: 'بیک اپ اور بحالی',
    admin.exportBackup: 'مکمل بیک اپ JSON ڈاؤن لوڈ کریں',
    admin.importBackup: 'بیک اپ JSON سے بحال کریں',
    admin.clearAll: 'پورا ڈیٹا صاف کریں',
  },
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'en'
    const stored = window.localStorage.getItem('shaibha-language') as Language | null
    return stored === 'ur' ? 'ur' : 'en'
  })

  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.localStorage.setItem('shaibha-language', language)
    }
  }, [language])

  const setLanguage = (next: Language) => setLanguageState(next)

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      isUrdu: language === 'ur',
      dir: language === 'ur' ? 'rtl' : 'ltr',
      setLanguage,
      t: (key: string) => translations[language][key] ?? translations.en[key] ?? key,
    }),
    [language],
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used within LanguageProvider')
  return context
}
